sudo: required

services:
 - docker

addons:
  apt:
    packages:
      - docker-ce=18.03* #Needed for experimental CLI (manifest)

language: bash

env:
  matrix:
  # TARGET_IMG  = Base image architecture to be used
  # TARGET_ARCH = qemu binary to be downloaded from https://github.com/multiarch/qemu-user-static/releases
  - TARGET_IMG=amd64   DOCKER_ARCH=amd64 QEMU_ARCH=amd64
  - TARGET_IMG=arm64v8 DOCKER_ARCH=arm64 QEMU_ARCH=aarch64
  - TARGET_IMG=arm32v6 DOCKER_ARCH=arm   QEMU_ARCH=arm

script:
- BUILD=true PUSH=false ./build.sh
- |
  if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
    # Push image
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    BUILD=false PUSH=true ./build.sh
  fi

jobs:
  include:
  - stage: Manifest
    script:
    - |
      mkdir -p $HOME/.docker
      echo '{"experimental": "enabled"}'>$HOME/.docker/config.json
    - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    - |
      if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        ARCHS="arm amd64 aarch64" BUILD=false PUSH=false MANIFEST=true ./build.sh
      fi
    env:
